import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import jumboImage from '../public/assets/img/bgjumbo.png'
import jumboImageLogo from '../public/assets/img/zlogo-bg.png'
import ArrowRight from '../public/assets/img/arrow-r.png';
import ArrowLeft from '../public/assets/img/arrow-l.png';
import React, { useEffect, useState } from 'react'
export default function Home() {
  useEffect(() => {
    const logos = document.getElementById('logo')
    const arrowRight = document.getElementById('a-right');
    const arrowLeft = document.getElementById('a-left');
    const mediaQuery = window.matchMedia("(max-width: 1200px)")
    const handleJumbotron = () => {
      if (mediaQuery.matches) {
        if (window.scrollY >= 90) {
          logos.style.transform = 'rotate(180deg)'
          arrowRight.style.right = '0px';
          arrowLeft.style.left = '0px';
        } else {
          logos.style.transform = 'rotate(0deg)';
          logos.style.transition = "all 2s";
          arrowRight.style.transition = "all 2s";
          arrowLeft.style.transition = "all 2s";
          arrowRight.style.right = '115px';
          arrowLeft.style.left = '115px';
        }
      } else {
        if (window.scrollY >= 90) {
          logos.style.transform = 'rotate(180deg)'
          arrowRight.style.right = '0px';
          arrowLeft.style.left = '0px';
        } else {
          logos.style.transform = 'rotate(0deg)';
          logos.style.transition = "all 2s";
          arrowRight.style.transition = "all 2s";
          arrowRight.style.right = '380px';
          arrowLeft.style.left = '380px';
          arrowLeft.style.transition = "all 2s";
        }
      }
    };
    window.addEventListener('scroll', handleJumbotron);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Zalira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href='https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap' />
      </Head>
      <main className={styles.main}>
        <section className='jumbotron rounded-lg bg-[url("../public/assets/img/net.jpg")] bg-no-repeat bg-cover bg-center mb-5 top-0 left-0 laptop:w-full laptop:h-96 tablet:w-full tablet:h-72 hp:w-full hp:h-40 relative'>
          <div className='rounded-lg mb-10 top-0 left-0 laptop:w-full laptop:h-96 tablet:w-full tablet:h-72 hp:w-full hp:h-40 bg-gradient-to-t from-stone-700 to-transparent z-40'></div>
          <Image src={jumboImage} className='laptop:ml-32 laptop:block tablet:hidden hp:hidden laptop:w-64 laptop:h-80 absolute m-auto top-0 left-0 bottom-0 fill-transparent z-4' alt='bgjumbo'></Image>
          <Image id='logo' src={jumboImageLogo} className='laptop:block hp:mt-3 absolute top-0 bottom-0 laptop:w-full laptop:h-full z-20' alt='bgjumbo'></Image>
          <Image id='a-right' src={ArrowRight} className='laptop:block laptop:w-32 laptop:h-32 hp:w-6 hp:h-6 absolute m-auto top-0 bottom-0 right-0 z-12' alt='arrowjumbo'></Image>
          <Image id='a-left' src={ArrowLeft} className='laptop:block laptop:w-32 laptop:h-32 hp:w-6 hp:h-6 absolute m-auto top-0 bottom-0 left-0 z-12' alt='arrowjumbo'></Image>
          <div className="inset-x-0 bottom-1/4 absolute">
            <h1 className='text-lg font-bold z-20 text-center'>Menyelesaikan masalah tanpa masalah</h1>
          </div>
        </section>
        <section className='problem h-auto text-center card bg-slate-400 w-full p-10 mb-3'>
          <h1 className='text-amber-300 text-6xl font-poppins'>Our Vision</h1>
          <h4 className='text-lg'>&quot;Membantu anda untuk menyelesaikan solusi&quot; </h4>
        </section>
        <section className='products mt-3 w-full'>
          <div className="card">
            {/* <marquee direction="left" hspace="20"> */}
              <div className="flex overflow-x-auto scroll-smooth hover:scroll-auto p-10 animate-marquee">
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
                <div className="card product flex-shrink-0 w-60 h-96 m-5 text-center p-4">
                  <Image src={jumboImage} alt="prod-1" className='w-full h-52 mb-4' />
                  <h3>Ebook Apps Cermin Muslim</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, unde. Pariatur, o</p>
                </div>
              </div>
            {/* </marquee> */}
          </div>
        </section>
      </main>
    </div>
  )
}
