import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import jumboImage from '../public/assets/img/bgjumbo.png'
import jumboImageLogo from '../public/assets/img/zlogo-bg.png'
import ArrowRight from '../public/assets/img/arrow-r.png';
import ArrowLeft from '../public/assets/img/arrow-l.png';
import React, { useEffect, useState } from 'react'
export default function Home() {
  useEffect(() => {
    const logos = document.getElementById('logo')
    const arrowRight = document.getElementById('a-right');
    const arrowLeft = document.getElementById('a-left');
    const handleJumbotron = () => {
      if (window.scrollY >= 90) {
        logos.style.transform = 'rotate(180deg)'
        arrowRight.style.right = '0px';
        arrowLeft.style.left = '0px';
      } else {
        logos.style.transform = 'rotate(0deg)';
        logos.style.transition = "all 2s";
        arrowRight.style.width = '150px';
        arrowRight.style.transition = "all 2s";
        arrowRight.style.right = '380px';
        arrowLeft.style.left = '380px';
        arrowLeft.style.width = '150px';
        arrowLeft.style.transition = "all 2s";
      }
    };
    window.addEventListener('scroll', handleJumbotron);
  }, []);
  return (
    <>
      <Head>
        <title>Zalira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className='jumbotron bg-[url("../public/assets/img/net.jpg")] bg-no-repeat bg-cover bg-center mb-10 top-0 left-0 laptop:w-full laptop:h-96 tablet:w-full tablet:h-72 hp:w-full hp:h-40 relative'>
          <div className='mb-10 top-0 left-0 laptop:w-full laptop:h-96 tablet:w-full tablet:h-72 hp:w-full hp:h-40 bg-gradient-to-t from-stone-700 to-transparent z-40'></div>
          <Image src={jumboImage} className='laptop:ml-32 laptop:block tablet:hidden hp:hidden laptop:w-64 laptop:h-80 absolute m-auto top-0 left-0 bottom-0 fill-transparent z-4' alt='bgjumbo'></Image>
          <Image id='logo' src={jumboImageLogo} className='laptop:block absolute top-0 bottom-0 laptop:w-full laptop:h-full z-20' alt='bgjumbo'></Image>
          <Image id='a-right' src={ArrowRight} className='laptop:block absolute laptop:w-50 laptop:h-50 m-auto top-0 bottom-0 right-0 z-12' alt='arrowjumbo'></Image>
          <Image id='a-left' src={ArrowLeft} width='50px' height='50px' className='laptop:block absolute m-auto top-0 bottom-0 left-0 z-12' alt='arrowjumbo'></Image>
          <div className='right-0 left-0 top-0 bottom-0 m-auto z-20 absolute'>
            <h1 className='text-lg font-bold'>Menyelesaikan masalah tanpa masalah</h1>
          </div>
        </section>
        <div div className={styles.container}>
          <section className='card left-0 right-0 m-auto w-full h-full absolute'>
            <h2>Okee Halaman 2</h2>
          </section>
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
        </div>
      </main>

    </>
  )
}
